
# Tests Actions to deploy ARM template to Azure
name: arm-template-deploy
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
      
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy arm template
      id: arm_deploy
      uses: mlopstemplates/arm_deploy@master
      with:
          resource_group: "testG" 
          template_file: "/.cloud/.azure/deploy.json"

    - name: Display deployment output details
      run: |
          echo deployment_status: "${{ steps.arm_deploy.outputs.deployment_status}}"
          echo deployment_error: "${{ steps.arm_deploy.outputs.deployment_error}}"
  
