
# Tests Actions to deploy ARM template to Azure
name: arm-template-deploy
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@master


    - name: deploy all resources
      id: aml_configure
      uses: mlopstemplates/aml_configure@v1.0
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          armtemplate_file: "deploy.json"
          armtemplateparams_file: "deploy.params.json"
          resource_group: ${{ secrets.AZURE_RESOURCE_GROUP }}

    - name: Display deployment output details
      run: |
          echo deployment_status: "${{ steps.arm_deploy.outputs.deployment_parameters}}"
          echo deployment_error: "${{ steps.arm_deploy.outputs.deployment_output}}"
  
